import type { Metadata } from "next";
import "../globals.css";
import FooterNav from "../components/FooterNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" data-theme="dark" dir="rtl" className="bg-[#202d46]">
      <body>
          <div className="flex flex-col">
            <div className='h-[90%]'>
              {children}
            </div>
            <div className='h-[10%]'>
              <FooterNav />
            </div>
          </div>
      </body>
    </html>
  );
}
